name: Build Handheld Executable

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install ARM Cross-Compiler and Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf

    - name: Compile Application for RG35XX (ARM)
      run: |
        make clean
        make CROSS_COMPILE=arm-linux-gnueabihf-

    - name: Upload Compiled Executable
      uses: actions/upload-artifact@v4
      with:
        name: simplermenu_plus_RG35XX
        path: output/
